// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Export(arg1:main.AppState,arg2:string):Promise<void>;

export function IsCalculating():Promise<boolean>;

export function LoadState():Promise<main.AppState>;

export function PerformCalculation(arg1:main.CalculationParams):Promise<main.CalculationResult>;

export function SaveState(arg1:main.AppState):Promise<void>;

export function ShowMessageDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StopCalculation():Promise<void>;
