// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Export(arg1, arg2) {
  return window['go']['main']['App']['Export'](arg1, arg2);
}

export function IsCalculating() {
  return window['go']['main']['App']['IsCalculating']();
}

export function LoadState() {
  return window['go']['main']['App']['LoadState']();
}

export function PerformCalculation(arg1) {
  return window['go']['main']['App']['PerformCalculation'](arg1);
}

export function SaveState(arg1) {
  return window['go']['main']['App']['SaveState'](arg1);
}

export function ShowMessageDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowMessageDialog'](arg1, arg2, arg3);
}

export function StopCalculation() {
  return window['go']['main']['App']['StopCalculation']();
}
