// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function IsCalculating():Promise<boolean>;

export function PerformCalculation(arg1:main.CalculationParams):Promise<main.CalculationResult>;

export function StopCalculation():Promise<void>;
