// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function IsCalculating():Promise<boolean>;

export function LoadState():Promise<main.AppState>;

export function PerformCalculation(arg1:main.CalculationParams):Promise<main.CalculationResult>;

export function SaveState(arg1:main.AppState):Promise<void>;

export function ShowAboutDialog():Promise<string>;

export function ShowHowToDialog():Promise<void>;

export function StopCalculation():Promise<void>;
